### PR TITLE
Add proposal template to .github/

### PR DESCRIPTION
**Pull request by lwjohnst86**

### CODE REVIEW

**Comment by lwjohnst86** [comment]
@gvwilson the nice thing about this template is that it automatically adds labels, assignees, etc.

**Comment by gvwilson** [comment]
This sounds good to me - put the use of multiple templates to a vote at Monday's meeting?

**Comment by gvwilson** [comment]
Should we discard #49 if this is accepted?

**Comment by lwjohnst86** [comment]
Yea, I think so. And discard this if not accepted :wink:

**Comment by lwjohnst86** [comment]
@gvwilson can you approve this so we can merge it in?

**Pull request merged**
