### PR TITLE
Template for proposals

### PR DESCRIPTION
**Pull request by gvwilson**
Small Markdown file to use when creating proposal issues.

### CODE REVIEW

**Comment by lwjohnst86** [comment]
Could this be put into `.github/ISSUE_TEMPLATE.md`? So it is automatic?

**Comment by gvwilson** [comment]
I thought about that, but it's not the only (or even usual) kind of issue, and as far as I know, GitHub only allows one template per repo (?).

**Comment by lwjohnst86** [comment]
You can create multiple issues when they are contained in `.github/ISSUE_TEMPLATE/template_name.md`. See [here](https://help.github.com/en/articles/creating-issue-templates-for-your-repository) for more explanation. I've tested it out on another project and it works fine. Only issue I have with it is that if you want to open a regular issue it just requires one extra click... which really isn't that big of a deal.

**Comment by gvwilson** [comment]
Closed in favor of #57.

**Pull request closed without merging**
