### PR TITLE
WIP: Bibliography issues

### PR DESCRIPTION
**Pull request by ljdursi**
First stab at #16 to improve bibliography.  Explicitly uses a common CSL file (for J Cell Biology) in both pdf and html outputs, which includes `note` fields

This PR will be complete when it addresses the three points listed in the issue:

- [ ] Single bibliography page in HTML format - this seems to be an RMarkdown thing
- [ ] Use a brief reference format 
- [x] Include notes field (although formatting improvements might be useful)

### CODE REVIEW

**Comment by lwjohnst86** [comment]
@ljdursi is this good to merge in?

**Comment by ljdursi** [comment]
I stopped work on this because it looked like you were doing similar work elsewhere, @gvwilson, and had a different approach?   I had actually meant to close this PR.

**Comment by gvwilson** [comment]
I thought I had figured this out in another repo (https://github.com/gvwilson/teachtogether.tech/), but I'm no longer sure what I'm doing is working - assign this to me and I'll dig?

**Comment by lwjohnst86** [comment]
@gvwilson any update on this? I can also take a stab at this, let me know.

**Comment by gvwilson** [comment]
I'm hoping to focus on content for the logging chapter in the next two weeks, so this one's yours if you want it - thanks.

**Comment by lwjohnst86** [comment]
Updated in #131

**Pull request closed without merging**
