### PR TITLE
Adding novels from Project Gutenberg as a possible dataset for textual analysis projects.

### PR DESCRIPTION
**Pull request by gvwilson**
-   former `project` directory renamed to `zipfs-law`.
-   `.gitignore` updated to ignore the `zipfs-law/results` directory.
-   Added `zipfs-law/data/README.md` (simple data manifest).

### CODE REVIEW

**Comment by elliewix** [comment]
I have used their copy of Dracula with my class for about three years now and know a bunch of interesting things you can analyze with that text. I also have a bunch of exercises related to it.

Also I don't know how to do reviews in github.

**Comment by gvwilson** [comment]
I think a comment like the one you just left is the kind of review something like this needs :-)

**Comment by ChristinaLK** [comment]
This looks cool! I have no idea what exercises I would use from it, but it sounds like @elliewix has that covered. ;)

**Comment by gvwilson** [comment]
@lwjohnst86 please merge - I think this is good to go.

**Pull request merged**
