### PR TITLE
Wrapping up chapter on publishing

### PR DESCRIPTION
**Pull request by gvwilson**
This chapter still feels a bit miscellaneous - I would be grateful for suggestions about how to overhaul it.

Depends on #413.

### CODE REVIEW

**Comment by DamienIrving** [comment]
I agree that this chapter doesn't fit well with the rest of the book and doesn't make for a great finish/climax. Maybe we should remove it altogether? 

Thinking about the content in the chapter and what to do with it instead...

### Content to remove from the book 
- Where to publish reports: This is not really relevant since the focus of the book is writing software, not reports
- Publishing data / FAIR principles: This is not really relevant since the focus of the book is writing software, not creating new datasets. There are also already good resources out there to explain the FAIR principles etc. 

### Content to put elsewhere in the book
- DOIs and ORCIDs: If we refer to these they can probably just be glossary items 
- Software journals: These could just be mentioned in a callout box in the packaging chapter
- Documenting software that isn't in a package (i.e. documenting your data processing workflow): This involves knowledge from the command line programs, automation (make), error handling (logging) and configuration chapters. If we're going to talk about it, then we probably want to do it right after those chapters rather than waiting until the very end of the book. We should also actually do it (i.e. document the workflow for plotting the collated word count distribution from all the books in `data/`) rather than just talking about how we'd theoretically/hypothetically document a data processing workflow.

**Comment by DamienIrving** [comment]
Expanding on that idea (of removing this chapter altogether and using some of the content elsewhere) there are essentially two major milestones in the narrative. The first is documenting the data processing workflow that we've built/run to plot the collated word count distribution (i.e. something Amira has done working more or less by herself), and the second is publishing the Zipf package to PyPI / Read the Docs and having the structures in place to work in a team with others (i.e. Amira opening her software up for others to use and contribute to going forward). In many instances a researcher writing a paper will stop at the first milestone, but if their software has wider appeal/application they'll go on to the second milestone. The order of the chapters (in `_py-rse.yml`) should maybe therefore be:
```
  - index.Rmd
  - py-rse/bash-basics.Rmd
  - py-rse/bash-advanced.Rmd
  - py-rse/scripting.Rmd
  - py-rse/git-cmdline.Rmd
  - py-rse/git-advanced.Rmd
  - py-rse/automate.Rmd
  - py-rse/config.Rmd
  - py-rse/errors.Rmd
  - py-rse/testing.Rmd
  - py-rse/provenance.Rmd   # Milestone 1 (i.e. working on your own up until here)
  - py-rse/project.Rmd
  - py-rse/packaging.Rmd
  - py-rse/teams.Rmd   # Milestone 2 (working with others)
  - py-rse/finale.Rmd

  - py-rse/style.Rmd    # not sure what the best place is for this? 
```

(I'm proposing a new chapter called `provenance.Rmd` which essentially takes the `#publish-software` section from `publish.Rmd` - minus the first bit about software journals - and talks about documenting what you did to create that figure/result.)

**Comment by k8hertweck** [comment]
I agree with @DamienIrving 's assessment of what to remove and what to put elsewhere; these topics are all at least mentioned elsewhere, and are also confounded with what would be put into the intro books, too. 

While I'm loathe to suggest a chapter reorganization at this point, I also think the two milestones are valid in the context of our audiences.

**Comment by lwjohnst86** [comment]
I agree with @DamienIrving as well, those are solid arguements for removing the chapter and rearranging content. +1

**Comment by k8hertweck** [comment]
I'm happy to put myself on the hook for some of the reorganization if we decide to do that (I've got a decent idea of what needs to be changed since I ran through most of the book adding `tree` commands. Alternatively, I can modify the proposals and/or pick up some of the other loose ends.

**Comment by DamienIrving** [comment]
@k8hertweck While you're reorganizing things I could have a go at creating the content for the new `provenance.md` chapter? The starting point will be the `#publish-software` section from the existing `publish.Rmd` chapter, but I can have a first go at editing it so that it actually documents the data processing steps involved in creating our collated word count distribution plot, rather than just talking about how we'd theoretically/hypothetically document a data processing workflow.

**Comment by cwickham** [comment]
I think the reorganization Damien proposes is a great idea!

**Comment by cwickham** [comment]
@DamienIrving  A suggestion for the content of `provenance.md`:

I like the mention of the GitHub Zenodo integration, but perhaps we can also mention the idea of git tags and GitHub releases.  E.g. Git tags provide a nice way to point at a specific commit. (Demonstrate usage). GitHub will use tags to provide releases, an easily downloaded snapshot of the repository at the tagged commit. (screenshots) You can even give GitHub releases a DOI through the GitHub Zenodo integration.

**Comment by DamienIrving** [comment]
@k8hertweck Actually, before you start reorganising I should sketch out in a bit more detail what will go in ‘provenance.md’... it might require some concepts that aren’t introduced until the packaging chapter, which complicates my proposal. Will do this tomorrow so I don’t hold things up.

**Comment by gvwilson** [comment]
I somehow overlooked `project.Rmd`, so I'm going to revise that next while y'all figure out where publishing stuff should go?

**Comment by SaraMati** [comment]
I think the reorganization and the two milestones is a great idea. I found learning a well documented data analysis workflow is essential for further use of the scripts.

**Pull request merged**
